# Generated by Django 5.0 on 2023-12-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupemail',
            name='is_guide_email',
        ),
    ]
