services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; bash run.sh'
    volumes:
      - ./local_settings.py:/opt/g10f/sso/apps/sso/settings/local_settings.py
      - media_data:/opt/g10f/sso/htdocs/media
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=sso
      - DATABASE_USER=sso
      - DATABASE_NAME=sso
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sso
      - POSTGRES_PASSWORD=sso
      - POSTGRES_DB=sso
volumes:
  postgres_data: {}
  media_data: {}