# Generated by Django 3.1.7 on 2021-03-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sso.auth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(blank=True, help_text='The human-readable name of this device.', max_length=255)),
                ('confirmed', models.BooleanField(default=False, help_text='Is this device ready for use?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this device was used?', null=True)),
                ('order', models.IntegerField(default=0, help_text='Overwrites the alphabetic order.')),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sso_auth.device')),
                ('key', models.CharField(default=sso.auth.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[sso.auth.models.key_validator])),
                ('step', models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.')),
                ('t0', models.BigIntegerField(default=0, help_text='The Unix time at which to begin counting steps.')),
                ('digits', models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8)], default=6, help_text='The number of digits to expect in a token.')),
                ('tolerance', models.PositiveSmallIntegerField(default=1, help_text='The number of time steps in the past or future to allow.')),
                ('drift', models.SmallIntegerField(default=0, help_text='The number of time steps the prover is known to deviate from our clock.')),
                ('last_t', models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=('sso_auth.device',),
        ),
        migrations.CreateModel(
            name='TwilioSMSDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sso_auth.device')),
                ('number', models.CharField(help_text='The mobile number to deliver tokens to.', max_length=16)),
                ('key', models.CharField(default=sso.auth.models.default_key, help_text='A random key used to generate tokens (hex-encoded).', max_length=40, validators=[sso.auth.models.key_validator])),
                ('last_t', models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=('sso_auth.device',),
        ),
        migrations.CreateModel(
            name='U2FDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sso_auth.device')),
                ('version', models.TextField(default='U2F_V2')),
                ('public_key', models.TextField()),
                ('key_handle', models.TextField()),
                ('app_id', models.TextField()),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=('sso_auth.device',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_otp_enabled', models.BooleanField(default=False, verbose_name='is otp enabled')),
                ('default_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sso_auth.device')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_auth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
