# Generated by Django 3.1.7 on 2021-04-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
        ('sso_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwilioSMSDevice',
        ),
    ]
