# Generated by Django 1.11.3 on 2017-07-02 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sso.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Is this device ready for use?'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Last time this device was used?', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='The human-readable name of this device.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='digits',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8)], default=6, help_text='The number of digits to expect in a token.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='drift',
            field=models.SmallIntegerField(default=0, help_text='The number of time steps the prover is known to deviate from our clock.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=sso.auth.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[sso.auth.models.key_validator]),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='last_t',
            field=models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='step',
            field=models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='t0',
            field=models.BigIntegerField(default=0, help_text='The Unix time at which to begin counting steps.'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='tolerance',
            field=models.PositiveSmallIntegerField(default=1, help_text='The number of time steps in the past or future to allow.'),
        ),
        migrations.AlterField(
            model_name='twiliosmsdevice',
            name='key',
            field=models.CharField(default=sso.auth.models.default_key, help_text='A random key used to generate tokens (hex-encoded).', max_length=40, validators=[sso.auth.models.key_validator]),
        ),
        migrations.AlterField(
            model_name='twiliosmsdevice',
            name='last_t',
            field=models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.'),
        ),
        migrations.AlterField(
            model_name='twiliosmsdevice',
            name='number',
            field=models.CharField(help_text='The mobile number to deliver tokens to.', max_length=16),
        ),
    ]
