# Generated by Django 3.2.10 on 2021-12-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0002_delete_twiliosmsdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u2fdevice',
            old_name='public_key',
            new_name='public_key_old',
        ),
    ]
