# Generated by Django 3.2.10 on 2021-12-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0003_rename_public_key_u2fdevice_public_key_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2fdevice',
            name='aaguid',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='u2fdevice',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='u2fdevice',
            name='credential_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='u2fdevice',
            name='public_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
