# Generated by Django 3.2.10 on 2021-12-26 23:35
from fido2 import cbor
from fido2.ctap2 import AttestedCredentialData
from fido2.utils import websafe_decode, websafe_encode

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    U2FDevice = apps.get_model("sso_auth", "U2FDevice")
    db_alias = schema_editor.connection.alias
    for d in U2FDevice.objects.using(db_alias).all():
        credential_data = AttestedCredentialData.from_ctap1(websafe_decode(d.key_handle), websafe_decode(d.public_key_old))

        d.public_key = websafe_encode(cbor.encode(credential_data.public_key))
        d.aaguid = websafe_encode(credential_data.aaguid)
        d.credential_id = websafe_encode(credential_data.credential_id)
        d.save()


def reverse_func(apps, schema_editor):
    U2FDevice = apps.get_model("sso_auth", "U2FDevice")
    db_alias = schema_editor.connection.alias
    for d in U2FDevice.objects.using(db_alias).all():
        d.public_key = ''
        d.aaguid = ''
        d.credential_id = ''
        d.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sso_auth', '0004_auto_20211227_1441'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
