# Generated by Django 3.2.10 on 2021-12-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0005_auto_20211227_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_deviceid',
            field=models.IntegerField(choices=[('U2FDevice', 1), ('TOTPDevice', 2)], default=None, null=True),
        ),
    ]
