# Generated by Django 3.2.10 on 2021-12-28 22:05

from django.db import migrations
from sso.auth.models import Device


def get_device_id(parent_device):
    for device in Device.devices:
        device_name = device[0].lower()
        if hasattr(parent_device, device_name):
            return device[1]


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    Profile = apps.get_model("sso_auth", "Profile")
    Device = apps.get_model("sso_auth", "Device")
    db_alias = schema_editor.connection.alias
    for p in Profile.objects.using(db_alias).all():
        device = Device.objects.using(db_alias).get(pk=p.default_device_id)
        p.default_deviceid = get_device_id(device)
        p.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0006_profile_default_deviceid'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
