# Generated by Django 3.2.10 on 2021-12-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0007_auto_20211228_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_device',
        ),
    ]
