# Generated by Django 3.2.10 on 2021-12-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0008_remove_profile_default_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_deviceid',
            new_name='default_device_id',
        ),
    ]
