# Generated by Django 3.2.10 on 2021-12-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0009_rename_default_deviceid_profile_default_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2fdevice',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='u2fdevice',
            name='key_handle',
        ),
        migrations.RemoveField(
            model_name='u2fdevice',
            name='public_key_old',
        ),
    ]
