# Generated by Django 3.2.11 on 2022-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0010_auto_20211229_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_device_id',
            field=models.IntegerField(choices=[('TOTPDevice', 2), ('U2FDevice', 1)], default=None, null=True),
        ),
    ]
