# Generated by Django 4.2.1 on 2023-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0012_auto_20220327_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_device_id',
            field=models.IntegerField(choices=[('TOTPDevice', 2), ('U2FDevice', 1)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='tolerance',
            field=models.PositiveSmallIntegerField(default=2, help_text='The number of time steps in the past or future to allow.'),
        ),
    ]
