# Generated by Django 4.2.1 on 2023-05-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0013_alter_profile_default_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpdevice',
            name='tolerance',
        ),
    ]
