# Generated by Django 4.2.4 on 2023-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0014_remove_totpdevice_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_device_id',
            field=models.IntegerField(choices=[('TOTPDevice', 2), ('U2FDevice', 1)], default=None, null=True),
        ),
    ]
