# Generated by Django 5.0.4 on 2024-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_auth', '0015_alter_profile_default_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_device_id',
            field=models.IntegerField(choices=[], default=None, null=True),
        ),
    ]
