# Generated by Django 3.1.7 on 2021-03-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2_code', models.CharField(max_length=2, unique=True, verbose_name='ISO alpha-2')),
                ('name', models.CharField(max_length=128, verbose_name='Official name (CAPS)')),
                ('printable_name', models.CharField(max_length=128, verbose_name='Country name')),
                ('iso3_code', models.CharField(max_length=3, unique=True, verbose_name='ISO alpha-3')),
                ('numcode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ISO numeric')),
                ('active', models.BooleanField(default=True, verbose_name='Country is active')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asia'), ('OC', 'Oceania'), ('SA', 'South America'), ('AN', 'Antarctica')], max_length=2, verbose_name='Continent')),
                ('admin_area', models.CharField(blank=True, choices=[('a', 'Another'), ('i', 'Island'), ('ar', 'Arrondissement'), ('at', 'Atoll'), ('ai', 'Autonomous island'), ('ca', 'Canton'), ('cm', 'Commune'), ('co', 'County'), ('dp', 'Department'), ('de', 'Dependency'), ('dt', 'District'), ('dv', 'Division'), ('em', 'Emirate'), ('gv', 'Governorate'), ('ic', 'Island council'), ('ig', 'Island group'), ('ir', 'Island region'), ('kd', 'Kingdom'), ('mu', 'Municipality'), ('pa', 'Parish'), ('pf', 'Prefecture'), ('pr', 'Province'), ('rg', 'Region'), ('rp', 'Republic'), ('sh', 'Sheading'), ('st', 'State'), ('sd', 'Subdivision'), ('sj', 'Subject'), ('ty', 'Territory')], max_length=2, null=True, verbose_name='Administrative Area')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Admin Area name')),
                ('abbrev', models.CharField(blank=True, max_length=3, null=True, verbose_name='Postal Abbreviation')),
                ('active', models.BooleanField(default=True, verbose_name='Area is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l10n.country')),
            ],
            options={
                'verbose_name': 'Administrative Area',
                'verbose_name_plural': 'Administrative Areas',
                'ordering': ('name',),
            },
        ),
    ]
