# Generated by Django 2.0.5 on 2018-05-17 20:47

import current_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('message', models.TextField(blank=True, help_text='Message for the administrators.', max_length=2048, verbose_name='message')),
                ('comment', models.TextField(blank=True, max_length=2048, verbose_name='Comment')),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'canceled'), ('v', 'approved'), ('d', 'denied')], default='o', max_length=255, verbose_name='status')),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessrequest_completed_by', to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('last_modified_by_user', current_user.models.CurrentUserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessrequest_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'last_modified',
                'verbose_name_plural': 'access request',
                'verbose_name': 'access request',
            },
        ),
    ]
