# Generated by Django 3.1.7 on 2021-03-28 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('message', models.TextField(blank=True, help_text='Message for the administrators.', max_length=2048, verbose_name='message')),
                ('comment', models.TextField(blank=True, max_length=2048, verbose_name='Comment')),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'canceled'), ('v', 'approved'), ('d', 'denied')], default='o', max_length=255, verbose_name='status')),
            ],
            options={
                'verbose_name': 'access request',
                'verbose_name_plural': 'access request',
                'get_latest_by': 'last_modified',
                'abstract': False,
            },
        ),
    ]
