apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sso.fullname" . }}-media
  labels:
    {{- include "sso.labels" . | nindent 4 }}
spec:
  {{- if not .Values.media.autoscaling.enabled }}
  replicas: {{ .Values.media.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sso.selectorLabelsMedia" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.media.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sso.selectorLabelsMedia" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html/media
              name: media
          resources:
            {{- toYaml .Values.media.resources | nindent 12 }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "sso.fullname" . }}-media
      {{- with .Values.media.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.media.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.media.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
