{{- if .Values.media.ingress.enabled -}}
{{- $fullName := include "sso.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-media
  labels:
    {{- include "sso.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Cache-Control "max-age=315360000, public, immutable";
      add_header access-control-allow-origin "*";
spec:
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-media
                port:
                  number: 80
{{- end }}
