apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso.fullname" . }}-media
  labels:
    {{- include "sso.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sso.selectorLabelsMedia" . | nindent 4 }}

