# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20150902_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationaddress',
            name='address_type',
            field=models.CharField(choices=[(b'meditation', 'Meditation Address'), (b'post', 'Post Only Address')], max_length=20, verbose_name='address type'),
        ),
    ]
