# Generated by Django 5.0.4 on 2024-05-10 10:04

import current_user.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisation_last_modified_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='last_modified_by_user',
            field=current_user.models.CurrentUserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
