# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20151212_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcountry',
            name='country_groups',
            field=models.ManyToManyField(blank=True, related_name='countries', to='organisations.CountryGroup'),
        ),
    ]
