# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20160129_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='neighbour_distance',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Nearest neighbour distance [m].', max_digits=8, null=True, verbose_name='neighbour distance'),
        ),
    ]
