# Generated by Django 5.2.17 on 2026-09-08 19:30

import sso.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_alter_organisation_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='google_plus_page',
        ),
        migrations.AddField(
            model_name='organisation',
            name='instagram_page',
            field=sso.fields.URLFieldEx(blank=True, domain='www.instagram.com', verbose_name='Instagram page'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='twitter_page',
            field=sso.fields.URLFieldEx(blank=True, domain='x.com', verbose_name='X page'),
        ),
    ]
