# Generated by Django 1.9.10 on 2016-10-23 12:11
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

from django.db import models, migrations
from sso.organisations.models import default_unique_slug_generator


def update_slug(apps, reverse=False):
    # We can't import the AdminRegion model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Model = apps.get_model("organisations", "AdminRegion")
    if reverse:
        objects = Model.objects.exclude(slug="")
        for obj in objects:
            obj.slug = ""
            obj.save(update_fields=['slug', 'last_modified'])
    else:
        objects = Model.objects.filter(slug="")
        for obj in objects:
            obj.slug = default_unique_slug_generator(slugify(obj.name), Model, obj)
            obj.save(update_fields=['slug', 'last_modified'])


def forward_update_slug(apps, schema_editor):
    update_slug(apps)


def reverse_update_slug(apps, schema_editor):
    update_slug(apps, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_adminregion_slug'),
    ]

    operations = [
        migrations.RunPython(forward_update_slug, reverse_code=reverse_update_slug),
    ]
