# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:33
from __future__ import unicode_literals

from django.db import migrations, connection
from django.conf import settings


def default_association(apps, reverse=False):
    Association = apps.get_model("organisations", "Association")

    if reverse:
        cursor = connection.cursor()
        cursor.execute("TRUNCATE TABLE organisations_association RESTART IDENTITY")

    else:
        association = Association(uuid=settings.SSO_DEFAULT_ASSOCIATION_UUID, name='Default')
        association.save()


def forward_default_association(apps, schema_editor):
    default_association(apps)


def reverse_default_association(apps, schema_editor):
    default_association(apps, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_association'),
    ]

    operations = [
        migrations.RunPython(forward_default_association, reverse_code=reverse_default_association),
    ]
