# Generated by Django 1.10.5 on 2017-02-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sso.organisations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_auto_20170219_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcountry',
            name='association',
            field=models.ForeignKey(default=sso.organisations.models.default_association, on_delete=django.db.models.deletion.CASCADE, to='organisations.Association', verbose_name='association'),
        ),
    ]
