# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_organisationcountry_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregion',
            name='organisation_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationCountry', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationCountry', verbose_name='country'),
        ),
    ]
