# Generated by Django 1.10.6 on 2017-03-03 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_auto_20170224_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='longitude',
        ),
    ]
