# Generated by Django 1.10.6 on 2017-03-12 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0020_auto_20170305_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='can_publish',
        ),
    ]
