# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0021_remove_organisation_can_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygroup',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='admin_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.AdminRegion', verbose_name='admin region'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, help_text='State or region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='l10n.AdminArea', verbose_name='State'),
        ),
    ]
