# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:32
from __future__ import unicode_literals

from django.db import migrations


def update_organisation(apps, reverse=False):
    Organisation = apps.get_model("organisations", "Organisation")

    if reverse:
        organisations = Organisation.objects.filter(association__isnull=False)
        for organisation in organisations:
            organisation.association = None
            organisation.save(update_fields=['association'])
    else:
        organisations = Organisation.objects.filter(association__isnull=True)
        for organisation in organisations:
            organisation.association = organisation.organisation_country.association
            organisation.save(update_fields=['association'])


def forward_update_organisation(apps, schema_editor):
    update_organisation(apps)


def reverse_update_organisation(apps, schema_editor):
    update_organisation(apps, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0023_auto_20170326_1936'),
    ]

    operations = [
        migrations.RunPython(forward_update_organisation, reverse_code=reverse_update_organisation),
    ]
