# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0025_auto_20170501_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_live',
            field=models.BooleanField(default=True, help_text='Designates whether this organisation is live. Unselect this for organisations which are prelive.', verbose_name='live'),
        ),
    ]
