# Generated by Django 2.0.1 on 2018-01-14 17:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import sso.organisations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0028_auto_20170702_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregion',
            name='email',
            field=models.OneToOneField(blank=True, limit_choices_to={'email_type': 'region'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='adminregion',
            name='organisation_country',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.OrganisationCountry', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='countrygroup',
            name='email',
            field=models.OneToOneField(blank=True, limit_choices_to={'email_type': 'global_region'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='admin_region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.AdminRegion', verbose_name='admin region'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='association',
            field=models.ForeignKey(default=sso.organisations.models.default_association, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Association', verbose_name='association'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.ForeignKey(blank=True, limit_choices_to={'email_type': 'center'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_country',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.OrganisationCountry', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='country',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='l10n.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organisationcountry',
            name='association',
            field=models.ForeignKey(default=sso.organisations.models.default_association, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='organisations.Association', verbose_name='association'),
        ),
        migrations.AlterField(
            model_name='organisationcountry',
            name='country',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='l10n.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organisationcountry',
            name='email',
            field=models.ForeignKey(blank=True, limit_choices_to={'email_type': 'country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email', verbose_name='email address'),
        ),
    ]
