# Generated by Django 2.0.6 on 2018-06-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0031_organisation_transregional_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationaddress',
            name='state',
        ),
    ]
