# Generated by Django 2.0.7 on 2018-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0032_remove_organisationaddress_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'get_latest_by': 'last_modified', 'ordering': ['order', 'name'], 'permissions': (('access_all_organisations', 'Can access all organisations'),), 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AddField(
            model_name='organisation',
            name='order',
            field=models.IntegerField(default=0, help_text='Overwrites the alphabetic order.'),
        ),
    ]
