# Generated by Django 3.1.7 on 2021-03-28 14:56

import current_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
                ('is_validated', models.BooleanField(db_index=True, default=False, help_text='Designates whether this profile was already validated by the user.', verbose_name='validated')),
                ('about_me', models.TextField(blank=True, max_length=1024, verbose_name='about_me')),
                ('known_person1_first_name', models.CharField(blank=True, max_length=100, verbose_name='first name of a known person')),
                ('known_person1_last_name', models.CharField(blank=True, max_length=100, verbose_name='last name of a known person')),
                ('known_person2_first_name', models.CharField(blank=True, max_length=100, verbose_name='first name of a another known person')),
                ('known_person2_last_name', models.CharField(blank=True, max_length=100, verbose_name='last name of a another known person')),
                ('check_back', models.BooleanField(default=False, help_text='Designates if there are open questions to check.', verbose_name='check back')),
                ('is_access_denied', models.BooleanField(db_index=True, default=False, help_text='Designates if access is denied to the user.', verbose_name='access denied')),
                ('comment', models.TextField(blank=True, max_length=2048, verbose_name='Comment')),
                ('last_modified_by_user', current_user.models.CurrentUserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrationprofile_last_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registration profile',
                'verbose_name_plural': 'registration profiles',
            },
        ),
    ]
