# Generated by Django 1.9.11 on 2016-11-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20150524_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Comment'),
        ),
    ]
