# Generated by Django 3.2.12 on 2022-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Whitespace separated list of post logout redirect uris.', verbose_name='post logout redirect uris'),
        ),
        migrations.AlterField(
            model_name='client',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Whitespace separated list of redirect uris.', verbose_name='redirect uris'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('web', 'Confidential client'), ('javascript', 'Implicit flow'), ('native', 'Public client'), ('service', 'Service account'), ('trusted', 'Trusted client')], default='web', max_length=255, verbose_name='type'),
        ),
    ]
