# Generated by Django 3.2.16 on 2022-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_auto_20220405_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Whitespace separated list of <a href="https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata">post logout redirect uris</a>.', verbose_name='post logout redirect uris'),
        ),
        migrations.AlterField(
            model_name='client',
            name='scopes',
            field=models.CharField(blank=True, default='openid profile email', help_text="Allowed space-delimited access token scopes ('openid', 'profile', 'email', 'role', 'role_profile', 'offline_access', 'address', 'phone', 'users', 'picture', 'events', 'tt')", max_length=512, verbose_name='scopes'),
        ),
    ]
