# Generated by Django 4.2 on 2023-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0003_auto_20221208_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='roles_type',
            field=models.CharField(blank=True, choices=[('list', 'List'), ('list-with-organisation', 'List with organisations')], max_length=255, verbose_name='Roles type'),
        ),
    ]
