# Generated by Django 1.10.6 on 2017-03-19 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0003_auto_20150607_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Application', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user, required for Client Credentials Grant', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
