# Generated by Django 4.2.4 on 2023-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_client_roles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='no_tokens_issued',
            field=models.IntegerField(default=0, verbose_name='number of tokens issued'),
        ),
    ]
