# Generated by Django 2.0.5 on 2018-05-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0007_client_is_trustworthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='bearer_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_token', to='oauth2.BearerToken', verbose_name='bearer token'),
        ),
    ]
