# Generated by Django 2.0.5 on 2018-05-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0008_auto_20180517_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='bearer_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='oauth2.BearerToken', verbose_name='bearer token'),
        ),
    ]
