# Generated by Django 2.0.5 on 2018-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0009_auto_20180520_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=128, verbose_name='code_challenge'),
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=4, verbose_name='code_challenge_method'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_using_pkce',
            field=models.BooleanField(default=False, help_text='Proof Key for Code Exchange for OAuth Public Clients <a href="https://tools.ietf.org/html/rfc7636">https://tools.ietf.org/html/rfc7636</a>', verbose_name='is using PKCE'),
        ),
    ]
