# Generated by Django 2.0.5 on 2018-05-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0011_auto_20180526_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='force_using_pkce',
            field=models.BooleanField(default=False, help_text='Enforce Proof Key for Code Exchange <a href="https://tools.ietf.org/html/rfc7636">https://tools.ietf.org/html/rfc7636</a>', verbose_name='force using PKCE'),
        ),
    ]
