# Generated by Django 2.2.7 on 2019-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0014_auto_20191116_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, verbose_name='post logout redirect uris'),
        ),
    ]
