# Generated by Django 3.1.7 on 2021-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0015_client_post_logout_redirect_uris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='scopes',
            field=models.CharField(blank=True, default='openid profile email', help_text="Allowed space-delimited access token scopes ('openid', 'profile', 'email', 'role', 'role_profile', 'offline_access', 'address', 'phone', 'users', 'picture', 'events')", max_length=512, verbose_name='scopes'),
        ),
    ]
