---
apiVersion: v1
kind: Pod
metadata:
  name: rsync
  labels:
    app: rsync
spec:
  containers:
  - image: g10f/rsync:1.0.7
    name: rsync-server
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "Europe/London"
      - name: USER_NAME
        value: "gunnar"
      - name: PUBLIC_KEY
        value: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAplohQ9tA63nxjM71huT/5mjrhZ9qJ6iwX0XlB2xJBxDgXEgkyA/fxr8QCM+4SFfNSto4TGAKw98fdT4dO2zrXWLgKe86vNia1E590m3iZUfACL5As3+3mU3OkbXANQhWSwB3wBFoh+9hVqlaFx6FjGpmS4VJ831TME0NLlnqd9Y+iDD+tK1X8FqjfHvhNCOgHctQaQDFKmYKaT8nVX64EtbYwkCUNuMukQnFbF30blIB+oBlhbingfgRq/zcQTi0bjgja2SdgD3RMSOVaAxlg2CopOASkoJaxCvaliWem+P+Rn8jG2SQ3t0Hq1Lz3UjiVsPQY4S5XZh2qYJD9yPKrQ=="
    ports:
      - name: ssh
        containerPort: 2222
        protocol: TCP
    volumeMounts:
      - mountPath: /opt/g10f/sso/htdocs/media
        name: media
        readOnly: true
  volumes:
    - name: media
      persistentVolumeClaim:
        claimName: sso-media
