apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sso.fullname" . }}-media
  labels:
    {{- include "sso.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
