apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso.fullname" . }}-backend-hl
  labels:
    {{- include "sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sso.selectorLabels" . | nindent 4 }}

