# Generated by Django 3.1.7 on 2021-03-28 14:56

import current_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationchange',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationchange',
            name='original_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_organisation', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onetimemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrole',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.application'),
        ),
        migrations.AddField(
            model_name='applicationrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='applicationadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationadmin',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.application', verbose_name='application'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_associations',
            field=models.ManyToManyField(blank=True, to='organisations.Association', verbose_name='admin associations'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_organisation_countries',
            field=models.ManyToManyField(blank=True, to='organisations.OrganisationCountry', verbose_name='admin countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_regions',
            field=models.ManyToManyField(blank=True, to='organisations.AdminRegion', verbose_name='admin regions'),
        ),
        migrations.AddField(
            model_name='user',
            name='app_admin_associations',
            field=models.ManyToManyField(blank=True, related_name='app_admin_user', to='organisations.Association', verbose_name='app admin associations'),
        ),
        migrations.AddField(
            model_name='user',
            name='app_admin_organisation_countries',
            field=models.ManyToManyField(blank=True, related_name='app_admin_user', to='organisations.OrganisationCountry', verbose_name='app admin countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='app_admin_regions',
            field=models.ManyToManyField(blank=True, related_name='app_admin_user', to='organisations.AdminRegion', verbose_name='app admin regions'),
        ),
        migrations.AddField(
            model_name='user',
            name='application_roles',
            field=models.ManyToManyField(blank=True, to='accounts.ApplicationRole', verbose_name='application roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified_by_user',
            field=current_user.models.CurrentUserField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(through='accounts.Membership', to='organisations.Organisation', verbose_name='organisations'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_profiles',
            field=models.ManyToManyField(blank=True, help_text='Organises a group of application roles that are usually assigned together.', to='accounts.RoleProfile', verbose_name='role profiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userattribute',
            index=models.Index(fields=['name', 'value'], name='accounts_us_name_a1c556_idx'),
        ),
        migrations.AddIndex(
            model_name='userattribute',
            index=models.Index(fields=['user'], name='accounts_us_user_id_455480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userattribute',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userassociatedsystem',
            unique_together={('application', 'userid')},
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address_type')},
        ),
        migrations.AlterUniqueTogether(
            name='roleprofileadmin',
            unique_together={('role_profile', 'admin')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationrole',
            unique_together={('application', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationadmin',
            unique_together={('application', 'admin')},
        ),
    ]
