# Generated by Django 3.1.7 on 2021-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210328_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stored_permanently',
            field=models.BooleanField(default=False, help_text='Do not delete, even if inactive', verbose_name='store permanently'),
        ),
    ]
