# Generated by Django 3.2.12 on 2022-04-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220406_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['order', 'title'], 'permissions': (('access_all_applications', 'Can access all applications'),), 'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
    ]
