# Generated by Django 3.2.16 on 2022-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.IntegerField(default=0, help_text='Overwrites the alphabetic order.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
