# Generated by Django 4.2.4 on 2023-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisation_timezone'),
        ('accounts', '0007_alter_user_language_alter_user_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(blank=True, through='accounts.Membership', to='organisations.organisation', verbose_name='organisations'),
        ),
    ]
