# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20151202_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last ip address'),
        ),
    ]
