# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Notes'),
        ),
    ]
