# Generated by Django 5.2.1 on 2025-05-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('read_user', 'Can read user data'), ('access_all_users', 'Can access all users'), ('app_admin_access_all_users', 'Can access all users as App admin'), ('reset_user_2fa', 'Can reset 2fa authentication for users')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
