# Generated by Django 1.10.5 on 2017-02-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_auto_20170224_2313'),
        ('accounts', '0011_auto_20161127_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_organisation_countries',
            field=models.ManyToManyField(blank=True, to='organisations.OrganisationCountry', verbose_name='admin countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='app_admin_organisation_countries',
            field=models.ManyToManyField(blank=True, related_name='app_admin_user', to='organisations.OrganisationCountry', verbose_name='app admin countries'),
        ),
    ]
