# Generated by Django 1.10.5 on 2017-02-26 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170226_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_countries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_admin_countries',
        ),
    ]
