# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170318_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Associated group for SSO internal permission management.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, help_text='State or region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='l10n.AdminArea', verbose_name='State'),
        ),
    ]
