# Generated by Django 1.10.6 on 2017-04-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0024_auto_20170326_2132'),
        ('accounts', '0017_auto_20170319_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_admin_associations',
            field=models.ManyToManyField(blank=True, related_name='app_admin_user', to='organisations.Association', verbose_name='app admin associations'),
        ),
    ]
