# Generated by Django 1.11.1 on 2017-05-25 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_app_admin_associations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationchange',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Comment'),
        ),
    ]
