# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 12:20
from __future__ import unicode_literals

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organisationchange_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimemessage',
            name='message',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='onetimemessage',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=255, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 40 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=40, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Business'), ('other', 'Other')], max_length=20, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\+\\d{1,3}((-?\\d+)|(\\s?\\(\\d+\\)\\s?)|\\s?\\d+){1,9}$', 32), 'Enter a valid phone number i.e. +49 (531) 123456', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_type',
            field=models.CharField(choices=[('home', 'Home'), ('mobile', 'Mobile'), ('work', 'Business'), ('fax', 'Fax'), ('pager', 'Pager'), ('other', 'Other')], help_text='Mobile, home, office, etc.', max_length=20, verbose_name='phone type'),
        ),
    ]
