# Generated by Django 2.0.2 on 2018-02-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180114_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationchange',
            old_name='reason',
            new_name='message',
        ),
    ]
