# Generated by Django 2.0.2 on 2018-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180224_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleprofile',
            name='is_organisation_related',
            field=models.BooleanField(default=False, help_text='Designates that the role will be deleted in case of a change of the organisation.', verbose_name='organisation related'),
        ),
        migrations.AlterField(
            model_name='organisationchange',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'canceled'), ('v', 'approved'), ('d', 'denied')], default='o', max_length=255, verbose_name='status'),
        ),
    ]
