# Generated by Django 2.0.6 on 2018-06-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20180303_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
    ]
