# Generated by Django 2.2.9 on 2020-02-01 10:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# noinspection PyPep8Naming
def migrate_to_usernotes(apps, reverse=False):
    User = apps.get_model("accounts", "User")
    UserNote = apps.get_model("accounts", "UserNote")

    if reverse:
        for user in User.objects.filter(usernote__isnull=False):
            user.notes = user.usernote_set.latest().note
            user.save(update_fields=['notes'])
    else:
        for user in User.objects.exclude(notes=""):
            UserNote.objects.create(user=user, note=user.notes)


def code(apps, schema_editor):
    migrate_to_usernotes(apps)


def reverse_code(apps, schema_editor):
    migrate_to_usernotes(apps, reverse=True)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0031_auto_20190709_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('note', models.TextField(max_length=1024, verbose_name='Note')),
                ('created_by_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user note',
                'verbose_name_plural': 'user notes',
                'get_latest_by': 'last_modified',
                'abstract': False,
            },
        ),
        migrations.RunPython(code=code, reverse_code=reverse_code),
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
    ]
