# Generated by Django 2.2.12 on 2020-04-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='internal'),
        ),
    ]
