# Generated by Django 2.2.12 on 2020-04-29 20:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_application_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='required_scope',
            field=models.CharField(blank=True, help_text='Required OAuth2 scope to get the application roles.', max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Required scope'),
        ),
    ]
