# Generated by Django 2.2.15 on 2020-08-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_application_required_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userattribute',
            index=models.Index(fields=['name', 'value'], name='accounts_us_name_a1c556_idx'),
        ),
        migrations.AddIndex(
            model_name='userattribute',
            index=models.Index(fields=['user'], name='accounts_us_user_id_455480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userattribute',
            unique_together={('user', 'name')},
        ),
    ]
